CREATE DATABASE Quan_Ly_Diem_Thi;
USE Quan_Ly_Diem_Thi;
CREATE TABLE Hoc_Sinh(
    MaHS VARCHAR(20) PRIMARY KEY,
    TenHS VARCHAR(50),
    NgaySinh DATETIME,
    Lop VARCHAR(20),
    GT VARCHAR(20)
);
CREATE TABLE Mon_Hoc(
    MaMH VARCHAR(20) PRIMARY KEY,
    TenMH VARCHAR(50)
);
CREATE TABLE Bang_Diem(
    MaHS VARCHAR(20),
    MaMH VARCHAR(20),
    DiemThi INT,
    NgayKT DATETIME,
    PRIMARY KEY (MaHS, MaMH),
    FOREIGN KEY (MaHS) REFERENCES Hoc_Sinh(MaHS),
    FOREIGN KEY (MaMH) REFERENCES Mon_Hoc(MaMH)
);
CREATE TABLE Giao_Vien(
    MaGV VARCHAR(20) PRIMARY KEY,
    TenGV VARCHAR(20),
    SDT VARCHAR(10)
);
ALTER TABLE Mon_Hoc ADD MaGV VARCHAR(20);
ALTER TABLE Mon_Hoc ADD CONSTRAINT FK_MaGV FOREIGN KEY (MaGV) REFERENCES Giao_Vien(MaGV);
